version: '2.1'

services:
  api:
    build:
      args:
        - NODE_ENV=development
    command: "npm run dev"
    environment:
      - EXPRESS_SERVER_PORT=8080
      - GRAPHQL_USE_MOCK_DATA
      - GRAPHQL_ENABLE_GRAPHIQL_ENDPOINT
      - NODE_ENV=development
    image: hrs-api:development
    command: npm run dev
    container_name: hrs_api
    ports:
      - ${HRS_PLUS_API_EXPOSED_HOST_PORT}:8080
      - 3123:3123
    volumes:
      - "./api:/app"
      - "/app/node_modules/"

  app:
    build:
      args:
        - NODE_ENV=development
    command: "npm run dev"
    environment:
      - EXPRESS_SERVER_PORT=8080
      - NODE_ENV=development
    image: hrs-app:development
    command: npm run dev
    container_name: hrs_app
    ports:
      - ${HRS_PLUS_APP_EXPOSED_HOST_PORT}:8080
    volumes:
      - "./app:/app"
      - "/app/node_modules/"
