version: '2.1'

services:
  openresty:
    image: "openresty/openresty:trusty"
    entrypoint: [/usr/local/openresty/bin/openresty, -c, /web/nginx.conf, -g, daemon off;]
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./web:/web
    networks:
      - esnet
    depends_on:
      - elasticsearch1

  redis:
    image: "redis:alpine"
    volumes:
      - ./data/redis:/data
    networks:
      - esnet
    ports:
     - "6379:6379"

  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.2
    container_name: elasticsearch1
    environment:
#      - cluster.name=docker-cluster
#      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms384m -Xmx384m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 640m
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet


  # elasticsearch1:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:6.0.0-beta1
  #   container_name: elasticsearch1
  #   environment:
  #     - cluster.name=docker-cluster
  #     - bootstrap.memory_lock=true
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   mem_limit: 1g
  #   volumes:
  #     - esdata1:/usr/share/elasticsearch/data
  #   ports:
  #     - 9200:9200
  #   networks:
  #     - esnet

  # elasticsearch2:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:6.0.0-beta1
  #   environment:
  #     - cluster.name=docker-cluster
  #     - bootstrap.memory_lock=true
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #     - "discovery.zen.ping.unicast.hosts=elasticsearch1"
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   mem_limit: 1g
  #   volumes:
  #     - esdata2:/usr/share/elasticsearch/data
  #   networks:
  #     - esnet

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local


networks:
  esnet:
    driver: bridge
    enable_ipv6: false
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.1
